"""Instrument-specific AI Drummer realization layer."""

from .comping import CompingPropensity, comping_propensity
from .model import (
    DrumGesture,
    DrumHit,
    DrummerRuntimeContext,
    DrummerSoftPlan,
    DrumVoice,
    GestureRole,
    Limb,
    TimeFeel,
)
from .pattern_corpus import (
    PATTERN_CORPUS,
    PatternHit,
    PatternUse,
    SourceRights,
    StoredDrumPattern,
    get_pattern,
    hits_at_current_position,
    patterns_with_tags,
)
from .pattern_runtime import pattern_gesture_now, source_pattern_candidates
from .interaction import (
    EnsembleMotifProjection,
    ResponseRelation,
    TradeCandidate,
    TradeLength,
    TradingPlan,
    build_trade_candidates,
    motif_similarity,
    perform_one_trade_gesture,
)
from .physical import (
    DEFAULT_LIMB_CAPABILITIES,
    LimbCapability,
    four_limb_solo_gesture,
    limb_can_play,
    validate_kit_reachability,
)
from .online_drummer import (
    DrummerPerformanceMemory,
    ScoredDrumGesture,
    build_immediate_candidates,
    perform_one_gesture,
    score_gesture,
)
from .solo import (
    DrumSoloPlan,
    DrumSoloState,
    SoloArc,
    SoloCandidate,
    SoloDevelopment,
    SOLO_VOCABULARY,
    SoloVocabularyCell,
    build_solo_candidates,
    perform_one_solo_gesture,
    solo_cell,
)
from .timing import (
    SwingTimingPrior,
    bounded_timing_offset_ms,
    is_ride_anchor,
    ride_positions_in_two_beat_cell,
    tempo_conditioned_swing_prior,
)

__all__ = [
    "CompingPropensity",
    "comping_propensity",
    "DrumGesture",
    "DrumHit",
    "DrummerRuntimeContext",
    "DrummerSoftPlan",
    "DrumVoice",
    "GestureRole",
    "Limb",
    "TimeFeel",
    "PATTERN_CORPUS",
    "PatternHit",
    "PatternUse",
    "SourceRights",
    "StoredDrumPattern",
    "get_pattern",
    "hits_at_current_position",
    "patterns_with_tags",
    "pattern_gesture_now",
    "source_pattern_candidates",
    "DrumSoloPlan",
    "DrumSoloState",
    "SoloArc",
    "SoloCandidate",
    "SoloDevelopment",
    "SOLO_VOCABULARY",
    "SoloVocabularyCell",
    "build_solo_candidates",
    "perform_one_solo_gesture",
    "solo_cell",
    "EnsembleMotifProjection",
    "ResponseRelation",
    "TradeCandidate",
    "TradeLength",
    "TradingPlan",
    "build_trade_candidates",
    "motif_similarity",
    "perform_one_trade_gesture",
    "DEFAULT_LIMB_CAPABILITIES",
    "LimbCapability",
    "four_limb_solo_gesture",
    "limb_can_play",
    "validate_kit_reachability",
    "DrummerPerformanceMemory",
    "ScoredDrumGesture",
    "build_immediate_candidates",
    "perform_one_gesture",
    "score_gesture",
    "SwingTimingPrior",
    "bounded_timing_offset_ms",
    "is_ride_anchor",
    "ride_positions_in_two_beat_cell",
    "tempo_conditioned_swing_prior",
]
