"""Transcription / notation workstream public API.

Performance Representation != Notation Representation.

This package consumes committed performance evidence and projects it through
notation intent/candidates into readable score structures and output adapters.
It must not contain player generation policy or duplicate Shared Core harmony /
ensemble reasoning.
"""

from .chord_chart import (
    BarlineStyle,
    ChartMeasure,
    ChordChange,
    ChordChart,
    ChordChartPosition,
    ChordSymbol,
    NavigationMark,
    chart_position,
)
from .events import (
    CommittedPerformanceEvent,
    ConfidenceBundle,
    EventAlternative,
    EvidenceKind,
    EvidenceRef,
    PerformanceCommitment,
    PerformedPitch,
    PerformanceTimeSpan,
    UnpitchedToken,
    commitment_value,
)
from .notation import (
    NotatedAtom,
    NotatedAtomKind,
    NotationCandidate,
    NotationIntent,
    NotationRelevance,
    ScoreSpan,
    TupletRatio,
    choose_preferred_candidate,
)
from .rhythm import (
    QuantizationGrid,
    quantize_score_span,
    rest_for_gap,
    split_note_across_bars,
    tuplet_note,
)
from .pipeline import (
    basic_rhythm_candidates,
    notation_intent_from_event,
    rhythm_candidate_from_event,
)
from .spelling import (
    AccidentalPreference,
    PitchSpellingCandidate,
    PitchSpellingContext,
    WrittenPitch,
    preferred_spelling,
    spelling_candidates,
)
from .allocation import (
    AllocationEvidence,
    StaffProfile,
    VoiceStaffCandidate,
    allocation_candidates,
    preferred_allocation,
)
from .piano import PianoGestureCandidate, piano_gesture_candidates
from .instrument_profiles import (
    ALTO,
    BASS,
    PERCUSSION,
    TENOR,
    TREBLE,
    ClefSpec,
    InstrumentProfile,
    TranspositionSpec,
    all_instrument_profiles,
    resolve_instrument_profile,
    written_range_warning,
)
from .instrument_rules import (
    InstrumentNotationDirective,
    NoteheadStyle,
    bass_notation_directive,
    drum_notation_directive,
    sax_notation_directive,
)
from .score import (
    GraceNoteKind,
    LogicalScore,
    LogicalScoreEvent,
    LogicalScorePart,
    ReadableScore,
    ScoreEvent,
    ScorePart,
    assemble_logical_score,
    assemble_score,
    extract_individual_part,
)
from .musicxml import score_to_musicxml
from .engraving import (
    BeamState,
    EngravingIntent,
    EngravingPlan,
    EngravingProfile,
    PrimaryBeamSide,
    StemDirection,
    TiePositionMode,
    TupletBracketMode,
    VerticalPlacement,
    beam_group_intents,
    build_default_engraving_plan,
    cross_staff_primary_beam_side,
    cross_staff_tie_placement,
    meter_beam_group,
    secondary_beam_group,
    secondary_beam_intents,
    tuplet_group_placement,
    voice_stem_directions,
)
from .layout import (
    AccidentalColumnDecision,
    GraceSpacingDecision,
    HorizontalSide,
    LayoutAction,
    LayoutActionKind,
    LayoutPressure,
    NoteheadDisplacementDecision,
    OpticalSpacingDecision,
    accidental_columns,
    grace_spacing_decisions,
    layout_actions,
    layout_pressures,
    notehead_displacements,
    optical_spacing_decisions,
)
from .engine import NotationEngine, NotationEngineConfig
from .quality import (
    QualityIssueSeverity,
    ScoreQualityIssue,
    ScoreQualityReport,
    audit_score_for_performance,
)
from .sequence import assemble_monophonic_voice
from .projection import (
    EventProjectionResult,
    dynamic_marking_from_level,
    project_pitched_event,
)

__all__ = [
    "BarlineStyle",
    "ChartMeasure",
    "ChordChange",
    "ChordChart",
    "ChordChartPosition",
    "ChordSymbol",
    "NavigationMark",
    "chart_position",
    "CommittedPerformanceEvent",
    "ConfidenceBundle",
    "EventAlternative",
    "EvidenceKind",
    "EvidenceRef",
    "PerformanceCommitment",
    "PerformedPitch",
    "PerformanceTimeSpan",
    "UnpitchedToken",
    "commitment_value",
    "NotatedAtom",
    "NotatedAtomKind",
    "NotationCandidate",
    "NotationIntent",
    "NotationRelevance",
    "ScoreSpan",
    "TupletRatio",
    "choose_preferred_candidate",
    "QuantizationGrid",
    "quantize_score_span",
    "rest_for_gap",
    "split_note_across_bars",
    "tuplet_note",
    "basic_rhythm_candidates",
    "notation_intent_from_event",
    "rhythm_candidate_from_event",
    "AccidentalPreference",
    "PitchSpellingCandidate",
    "PitchSpellingContext",
    "WrittenPitch",
    "preferred_spelling",
    "spelling_candidates",
    "AllocationEvidence",
    "StaffProfile",
    "VoiceStaffCandidate",
    "allocation_candidates",
    "preferred_allocation",
    "PianoGestureCandidate",
    "piano_gesture_candidates",
    "ALTO",
    "BASS",
    "PERCUSSION",
    "TENOR",
    "TREBLE",
    "ClefSpec",
    "InstrumentProfile",
    "TranspositionSpec",
    "all_instrument_profiles",
    "resolve_instrument_profile",
    "written_range_warning",
    "InstrumentNotationDirective",
    "NoteheadStyle",
    "bass_notation_directive",
    "drum_notation_directive",
    "sax_notation_directive",
    "GraceNoteKind",
    "LogicalScore",
    "LogicalScoreEvent",
    "LogicalScorePart",
    "ReadableScore",
    "ScoreEvent",
    "ScorePart",
    "assemble_logical_score",
    "assemble_score",
    "extract_individual_part",
    "score_to_musicxml",
    "BeamState",
    "EngravingIntent",
    "EngravingPlan",
    "EngravingProfile",
    "PrimaryBeamSide",
    "StemDirection",
    "TiePositionMode",
    "TupletBracketMode",
    "VerticalPlacement",
    "beam_group_intents",
    "build_default_engraving_plan",
    "cross_staff_primary_beam_side",
    "cross_staff_tie_placement",
    "meter_beam_group",
    "secondary_beam_group",
    "secondary_beam_intents",
    "tuplet_group_placement",
    "voice_stem_directions",
    "AccidentalColumnDecision",
    "GraceSpacingDecision",
    "HorizontalSide",
    "LayoutAction",
    "LayoutActionKind",
    "LayoutPressure",
    "NoteheadDisplacementDecision",
    "OpticalSpacingDecision",
    "accidental_columns",
    "grace_spacing_decisions",
    "layout_actions",
    "layout_pressures",
    "notehead_displacements",
    "optical_spacing_decisions",
    "NotationEngine",
    "NotationEngineConfig",
    "QualityIssueSeverity",
    "ScoreQualityIssue",
    "ScoreQualityReport",
    "audit_score_for_performance",
    "assemble_monophonic_voice",
    "EventProjectionResult",
    "dynamic_marking_from_level",
    "project_pitched_event",
]

from .scorebook_ingestion import (
    ObservedChord,
    ObservedMeasure,
    PageAnnotation,
    ScorebookIngestionResult,
    ScorebookPageObservation,
    compile_scorebook_observation,
    evidence_summary,
)
