"""Shared, instrument-neutral jazz harmony intelligence."""

from .jazz_harmony_core import (
    HarmonicAffordance,
    HarmonicEvidence,
    HarmonicFrame,
    HarmonicIntent,
    HarmonySource,
    TensionChoice,
    build_basic_affordances,
)
from .functional_graph import (
    FunctionFamily,
    FunctionalEdge,
    FunctionalNode,
    HarmonicFunctionGraph,
    MetricStress,
    ResolutionKind,
    dominant_expected_resolution,
    infer_dominant_family,
    make_resolution_edge,
)
from .contextual_tension import (
    MusicalLayer,
    TensionAssessment,
    TensionContext,
    TensionUse,
    assess_tension,
)
from .voice_leading import (
    MotionType,
    ResolutionDebt,
    TargetRole,
    VoiceLeadingAssessment,
    VoiceLeadingContext,
    VoiceMotion,
    VoiceRole,
    VoiceState,
    assess_voice_leading,
    make_resolution_debt,
)
from .modal_nonfunctional import (
    ContinuityMechanism,
    HarmonicOrientation,
    ModalAssessment,
    ModalState,
    NonfunctionalAssessment,
    NonfunctionalState,
    VerticalTopology,
    assess_modal_state,
    assess_nonfunctional_state,
    modal_characteristic_pc,
)

__all__ = [
    "HarmonicAffordance",
    "HarmonicEvidence",
    "HarmonicFrame",
    "HarmonicIntent",
    "HarmonySource",
    "TensionChoice",
    "build_basic_affordances",
    "FunctionFamily",
    "FunctionalEdge",
    "FunctionalNode",
    "HarmonicFunctionGraph",
    "MetricStress",
    "ResolutionKind",
    "dominant_expected_resolution",
    "infer_dominant_family",
    "make_resolution_edge",
    "MusicalLayer",
    "TensionAssessment",
    "TensionContext",
    "TensionUse",
    "assess_tension",
    "MotionType",
    "ResolutionDebt",
    "TargetRole",
    "VoiceLeadingAssessment",
    "VoiceLeadingContext",
    "VoiceMotion",
    "VoiceRole",
    "VoiceState",
    "assess_voice_leading",
    "make_resolution_debt",
    "ContinuityMechanism",
    "HarmonicOrientation",
    "ModalAssessment",
    "ModalState",
    "NonfunctionalAssessment",
    "NonfunctionalState",
    "VerticalTopology",
    "assess_modal_state",
    "assess_nonfunctional_state",
    "modal_characteristic_pc",
]
