"""Shared abstract musical vocabulary catalog.

This catalog collects reusable musical *behaviors* already encoded elsewhere in
RealSolo. It is intentionally broader than Legend vocabulary.

Important:
- no copyrighted literal phrase is reconstructed here;
- source-derived items are abstracted to reusable dimensions/tags;
- exact source patterns whose rights are research/reference-only stay in their
  source corpus and are not copied into this runtime catalog;
- Player-specific mechanics remain in Players.
"""
from __future__ import annotations

from dataclasses import dataclass

from music_intelligence.legends.interfaces import (
    LegendDomain,
    SignatureStatus,
    VocabularyDimension,
    VocabularyMemoryItem,
    VocabularyQuery,
    VocabularyUseType,
)
from .retrieval import rank_vocabulary_items


_ABSTRACT_USES=frozenset({
    VocabularyUseType.ADAPTED_LICK,
    VocabularyUseType.FRAGMENT_RECALL,
    VocabularyUseType.ABSTRACTED_PATTERN,
    VocabularyUseType.HYBRID_COMPOSITION,
})


def _item(
    vocabulary_id: str,
    *,
    source_id: str,
    rhythm: str="",
    contour: str="",
    interval_pattern: str="",
    articulation: str="",
    register: str="",
    tension_curve: str="",
    source_instrument: str="",
    dimensions: tuple[VocabularyDimension,...]=(),
    transferable_to: tuple[str,...]=(),
    domains: tuple[LegendDomain,...]=(),
    tags: tuple[str,...]=(),
    harmony_context: str="",
    harmonic_function: str="",
    phrase_position: str="",
    confidence: float=.75,
    provenance: tuple[str,...]=(),
) -> VocabularyMemoryItem:
    item=VocabularyMemoryItem(
        vocabulary_id=vocabulary_id,
        source_id=source_id,
        transposition_normalized_representation="abstract_only",
        harmony_context=harmony_context,
        harmonic_function=harmonic_function,
        phrase_position=phrase_position,
        rhythm=rhythm,
        contour=contour,
        interval_pattern=interval_pattern,
        articulation=articulation,
        register=register,
        tension_curve=tension_curve,
        source_instrument=source_instrument,
        dimensions=frozenset(dimensions),
        transferable_to=frozenset(transferable_to),
        domains=frozenset(domains),
        context_tags=frozenset(tags),
        candidate_uses=_ABSTRACT_USES,
        signature_status=SignatureStatus.NONE,
        confidence=confidence,
        provenance=provenance,
    )
    item.validate()
    return item


SHARED_VOCABULARY_ITEMS: tuple[VocabularyMemoryItem,...]=(
    # ----- Generic solo-development vocabulary -----
    _item("shared.solo.state",
        source_id="core:solo_grammar",
        contour="preserve current identity",
        dimensions=(VocabularyDimension.PHRASE_SHAPE,),
        domains=(LegendDomain.MOTIF_DEVELOPMENT,LegendDomain.REPETITION_VARIATION),
        tags=("solo","state","identity"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute","vocal"),
        confidence=.95, provenance=("shared_solo_grammar",)),
    _item("shared.solo.vary",
        source_id="core:solo_grammar",
        contour="variation of active identity",
        dimensions=(VocabularyDimension.PHRASE_SHAPE,VocabularyDimension.CONTOUR),
        domains=(LegendDomain.MOTIF_DEVELOPMENT,LegendDomain.REPETITION_VARIATION),
        tags=("solo","vary","motif"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute","vocal"),
        confidence=.95, provenance=("shared_solo_grammar",)),
    _item("shared.solo.fragment",
        source_id="core:solo_grammar",
        rhythm="partial recall",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.MOTIF_DEVELOPMENT,LegendDomain.REPETITION_VARIATION),
        tags=("solo","fragment","motif"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute","vocal"),
        confidence=.95, provenance=("shared_solo_grammar",)),
    _item("shared.solo.sequence",
        source_id="core:solo_grammar",
        contour="sequential development",
        dimensions=(VocabularyDimension.PITCH_INTERVAL,VocabularyDimension.CONTOUR,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.MOTIF_DEVELOPMENT,LegendDomain.LINEAR_CONNECTION),
        tags=("solo","sequence","develop"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute"),
        confidence=.95, provenance=("shared_solo_grammar",)),
    _item("shared.solo.displace",
        source_id="core:solo_grammar",
        rhythm="rhythmic displacement",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.ACCENT),
        domains=(LegendDomain.RHYTHM_SUBDIVISION,LegendDomain.MOTIF_DEVELOPMENT),
        tags=("solo","displace","rhythmic_displacement"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","drums","trumpet","guitar","flute","vocal"),
        confidence=.95, provenance=("shared_solo_grammar",)),
    _item("shared.solo.add_space",
        source_id="core:solo_grammar",
        rhythm="intentional phrase space",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.DENSITY_ARC,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.BREATH_SPACE,LegendDomain.PHRASE_ENDING),
        tags=("solo","ensemble_space","add_space"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","drums","trumpet","guitar","flute","vocal"),
        confidence=.98, provenance=("shared_solo_grammar",)),
    _item("shared.solo.target_next_harmony",
        source_id="core:solo_grammar",
        contour="directed motion into future harmony",
        tension_curve="prepare -> target -> release",
        dimensions=(VocabularyDimension.TARGET_BEHAVIOR,VocabularyDimension.TENSION_RELEASE,VocabularyDimension.CONTOUR),
        domains=(LegendDomain.FUTURE_HARMONY_AWARENESS,LegendDomain.HARMONY_TARGET_SELECTION,LegendDomain.TENSION_RELEASE),
        tags=("solo","future_harmony","directed_target"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute","vocal"),
        confidence=.98, provenance=("shared_solo_grammar",)),
    _item("shared.solo.answer",
        source_id="core:solo_grammar",
        rhythm="response after ensemble opening",
        dimensions=(VocabularyDimension.INTERACTION_ROLE,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.CALL_RESPONSE,LegendDomain.ENSEMBLE_INTERACTION),
        tags=("solo","answer","call_response"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","drums","trumpet","guitar","flute","vocal"),
        confidence=.95, provenance=("shared_solo_grammar",)),
    _item("shared.solo.recap_resolve",
        source_id="core:solo_grammar",
        contour="recover identity then resolve",
        tension_curve="release",
        dimensions=(VocabularyDimension.PHRASE_SHAPE,VocabularyDimension.TENSION_RELEASE),
        domains=(LegendDomain.PHRASE_ENDING,LegendDomain.MOTIF_DEVELOPMENT,LegendDomain.TENSION_RELEASE),
        tags=("solo","recap","resolve","phrase_end"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute","vocal"),
        confidence=.95, provenance=("shared_solo_grammar",)),

    # ----- Bebop / linear-language vocabulary already encoded in Parker/shared linear work -----
    _item("shared.bebop.passing_connection",
        source_id="promoted:parker+shared_linear",
        contour="close linear connection",
        interval_pattern="stepwise / within P4 tendency",
        dimensions=(VocabularyDimension.PITCH_INTERVAL,VocabularyDimension.CONTOUR),
        domains=(LegendDomain.LINEAR_CONNECTION,),
        tags=("jazz","bebop","passing","voice_leading"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute"),
        confidence=.92, provenance=("PARKER_PROFILE_VIEW","shared_scale_linear_core")),
    _item("shared.bebop.neighbor_motion",
        source_id="promoted:parker",
        contour="neighbor motion around stable target",
        dimensions=(VocabularyDimension.PITCH_INTERVAL,VocabularyDimension.CONTOUR),
        domains=(LegendDomain.LINEAR_CONNECTION,),
        tags=("jazz","bebop","neighbor"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute"),
        confidence=.90, provenance=("PARKER_PROFILE_VIEW",)),
    _item("shared.bebop.close_approach",
        source_id="promoted:parker",
        contour="semitone/step approach to target",
        tension_curve="approach -> target",
        dimensions=(VocabularyDimension.PITCH_INTERVAL,VocabularyDimension.TARGET_BEHAVIOR,VocabularyDimension.TENSION_RELEASE),
        domains=(LegendDomain.LINEAR_CONNECTION,LegendDomain.HARMONY_TARGET_SELECTION),
        tags=("jazz","bebop","close_approach","directed_target"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute"),
        confidence=.94, provenance=("PARKER_PROFILE_VIEW",)),
    _item("shared.bebop.enclosure_target",
        source_id="core:scale_linear+parker_research",
        contour="surround then resolve to target",
        tension_curve="local tension -> target",
        dimensions=(VocabularyDimension.PITCH_INTERVAL,VocabularyDimension.TARGET_BEHAVIOR,VocabularyDimension.TENSION_RELEASE),
        domains=(LegendDomain.LINEAR_CONNECTION,LegendDomain.TENSION_RELEASE),
        tags=("jazz","bebop","enclosure","directed_target"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute"),
        confidence=.91, provenance=("shared_scale_linear_core","PARKER_PROFILE_VIEW")),
    _item("shared.bebop.anticipation",
        source_id="promoted:parker",
        rhythm="meaningful offbeat or late entry",
        contour="anticipate next harmony",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.TARGET_BEHAVIOR),
        domains=(LegendDomain.FUTURE_HARMONY_AWARENESS,LegendDomain.PHRASE_ENTRANCE),
        tags=("jazz","bebop","anticipation","future_harmony"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute"),
        confidence=.94, provenance=("PARKER_PROFILE_VIEW",)),
    _item("shared.bebop.altered_resolution",
        source_id="promoted:parker",
        contour="altered color with audible directed resolution",
        tension_curve="intensify -> resolution_path",
        dimensions=(VocabularyDimension.TENSION_RELEASE,VocabularyDimension.TARGET_BEHAVIOR),
        domains=(LegendDomain.TENSION_RELEASE,LegendDomain.HARMONY_TARGET_SELECTION),
        tags=("jazz","bebop","altered","resolution_path","directed_target"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar"),
        confidence=.92, provenance=("PARKER_PROFILE_VIEW",)),
    _item("shared.bebop.syncopated_long_tone",
        source_id="promoted:parker",
        rhythm="held note energized by offbeat/anticipated entry",
        articulation="connected held tone",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.ARTICULATION,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.PHRASE_ENTRANCE,LegendDomain.RHYTHM_SUBDIVISION),
        tags=("jazz","bebop","syncopated_long_tone","anticipation"),
        transferable_to=("tenor_sax","alto_saxophone","trumpet","flute","vocal","guitar"),
        confidence=.94, provenance=("PARKER_PROFILE_VIEW",)),
    _item("shared.bebop.contextual_triplet",
        source_id="promoted:parker",
        rhythm="triplet as contextual insertion, not constant surface",
        dimensions=(VocabularyDimension.RHYTHM,),
        domains=(LegendDomain.RHYTHM_SUBDIVISION,),
        tags=("jazz","bebop","triplet","subdivision_variation"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","drums","trumpet","guitar","flute","vocal"),
        confidence=.88, provenance=("PARKER_PROFILE_VIEW",)),
    _item("shared.bebop.wide_leap_recovery",
        source_id="promoted:parker",
        contour="rare wide leap followed by contrary/close recovery",
        interval_pattern="wide event -> recover within P4",
        dimensions=(VocabularyDimension.PITCH_INTERVAL,VocabularyDimension.CONTOUR),
        domains=(LegendDomain.INTERVAL_LEAP_GRAMMAR,LegendDomain.LINEAR_CONNECTION),
        tags=("jazz","bebop","wide_leap","contrary_recovery","recovery_within_p4"),
        transferable_to=("tenor_sax","alto_saxophone","piano","bass","trumpet","guitar","flute"),
        confidence=.90, provenance=("PARKER_PROFILE_VIEW",)),

    # ----- Bass vocabulary already encoded in canonical Bass grammar -----
    _item("shared.bass.walk_anchor",
        source_id="player:bass_performance_grammar",
        rhythm="quarter-note walking spine",
        contour="beat-one harmonic anchor",
        source_instrument="bass",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.TARGET_BEHAVIOR),
        domains=(LegendDomain.HARMONY_TARGET_SELECTION,LegendDomain.FORM_AWARENESS),
        tags=("jazz","walking","harmonic_anchor","root"),
        transferable_to=("bass","electric_bass"),
        confidence=.96, provenance=("players/bass/performance_grammar.py",)),
    _item("shared.bass.walk_middle_motion",
        source_id="player:bass_performance_grammar",
        rhythm="middle walking beats develop line",
        contour="chord member / shared scale / color",
        source_instrument="bass",
        dimensions=(VocabularyDimension.CONTOUR,VocabularyDimension.PITCH_INTERVAL),
        domains=(LegendDomain.LINEAR_CONNECTION,),
        tags=("jazz","walking","continuation","chordal","scale_color"),
        transferable_to=("bass","electric_bass"),
        confidence=.96, provenance=("players/bass/performance_grammar.py",)),
    _item("shared.bass.last_beat_approach",
        source_id="player:bass_performance_grammar",
        rhythm="last-beat preparation",
        contour="chromatic or direct approach to next root",
        source_instrument="bass",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.TARGET_BEHAVIOR,VocabularyDimension.PITCH_INTERVAL),
        domains=(LegendDomain.FUTURE_HARMONY_AWARENESS,LegendDomain.LINEAR_CONNECTION),
        tags=("jazz","walking","preparation","chromatic_approach","anticipation"),
        transferable_to=("bass","electric_bass"),
        confidence=.97, provenance=("players/bass/performance_grammar.py",)),
    _item("shared.bass.stepwise_connector",
        source_id="player:bass_performance_grammar",
        contour="stepwise connective motion",
        source_instrument="bass",
        dimensions=(VocabularyDimension.PITCH_INTERVAL,VocabularyDimension.CONTOUR),
        domains=(LegendDomain.LINEAR_CONNECTION,),
        tags=("jazz","walking","stepwise_connection"),
        transferable_to=("bass","electric_bass"),
        confidence=.92, provenance=("players/bass/performance_grammar.py",)),
    _item("shared.bass.two_feel_direction",
        source_id="player:bass_performance_grammar",
        rhythm="two-feel anchor then directional second pulse",
        contour="root/fifth support with movement on second pulse",
        source_instrument="bass",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.CONTOUR),
        domains=(LegendDomain.RHYTHM_SUBDIVISION,LegendDomain.FORM_AWARENESS),
        tags=("jazz","two_feel","root","fifth","direction"),
        transferable_to=("bass","electric_bass"),
        confidence=.94, provenance=("players/bass/performance_grammar.py",)),
    _item("shared.bass.ghost_offbeat",
        source_id="player:bass_ghost_notes",
        rhythm="optional swung offbeat ghost/dead note",
        articulation="ghosted/dead",
        source_instrument="bass",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.ARTICULATION),
        domains=(LegendDomain.RHYTHM_SUBDIVISION,LegendDomain.ARTICULATION),
        tags=("jazz","walking","eighth_offbeat","ghost_note"),
        transferable_to=("bass","electric_bass"),
        confidence=.90, provenance=("players/bass/ghost_notes.py",)),
    _item("shared.bass.phrase_build_release",
        source_id="player:bass_phrase_intent",
        contour="ground -> develop -> build -> release",
        tension_curve="controlled phrase arc",
        source_instrument="bass",
        dimensions=(VocabularyDimension.DENSITY_ARC,VocabularyDimension.REGISTER_TRAJECTORY,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.FORM_AWARENESS,LegendDomain.REGISTER_TRAJECTORY),
        tags=("jazz","bass","phrase_arc","develop","build","release"),
        transferable_to=("bass","electric_bass"),
        confidence=.93, provenance=("players/bass/phrase_intent.py",)),

    # ----- Piano comping vocabulary already encoded in comping evaluator -----
    _item("shared.piano.lay_out",
        source_id="player:piano_comping",
        rhythm="intentional silence under busy foreground",
        source_instrument="piano",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.DENSITY_ARC,VocabularyDimension.INTERACTION_ROLE),
        domains=(LegendDomain.BREATH_SPACE,LegendDomain.ENSEMBLE_INTERACTION),
        tags=("jazz","comping","lay_out","ensemble_space"),
        transferable_to=("piano","guitar"),
        confidence=.96, provenance=("players/piano/comping.py",)),
    _item("shared.piano.sparse_support",
        source_id="player:piano_comping",
        rhythm="sparse supportive comping",
        source_instrument="piano",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.DENSITY_ARC,VocabularyDimension.INTERACTION_ROLE),
        domains=(LegendDomain.ENSEMBLE_INTERACTION,),
        tags=("jazz","comping","support","sparse"),
        transferable_to=("piano","guitar"),
        confidence=.96, provenance=("players/piano/comping.py",)),
    _item("shared.piano.answer_fill",
        source_id="player:piano_comping",
        rhythm="answer/fill in available phrase space",
        source_instrument="piano",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.INTERACTION_ROLE,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.CALL_RESPONSE,LegendDomain.ENSEMBLE_INTERACTION),
        tags=("jazz","comping","answer","fill","call_response"),
        transferable_to=("piano","guitar"),
        confidence=.95, provenance=("players/piano/comping.py",)),
    _item("shared.piano.punctuation",
        source_id="player:piano_comping",
        rhythm="short punctuation around structural opening",
        articulation="short/accented",
        source_instrument="piano",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.ARTICULATION,VocabularyDimension.INTERACTION_ROLE),
        domains=(LegendDomain.FORM_AWARENESS,LegendDomain.ENSEMBLE_INTERACTION),
        tags=("jazz","comping","punctuation","accent"),
        transferable_to=("piano","guitar"),
        confidence=.93, provenance=("players/piano/comping.py",)),
    _item("shared.piano.harmonic_continuity",
        source_id="player:piano_harmonic_continuity",
        contour="voice-leading continuity across harmony",
        source_instrument="piano",
        dimensions=(VocabularyDimension.PITCH_INTERVAL,VocabularyDimension.TARGET_BEHAVIOR),
        domains=(LegendDomain.LINEAR_CONNECTION,LegendDomain.HARMONY_TARGET_SELECTION),
        tags=("jazz","comping","voice_leading","harmonic_continuity"),
        transferable_to=("piano","guitar"),
        confidence=.95, provenance=("players/piano/harmonic_continuity.py","players/piano/lh_voice_leading.py")),
    _item("shared.piano.texture_release",
        source_id="player:piano_texture_control",
        rhythm="texture/density release after sustained activity",
        source_instrument="piano",
        dimensions=(VocabularyDimension.DENSITY_ARC,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.BREATH_SPACE,LegendDomain.FORM_AWARENESS),
        tags=("jazz","comping","release","texture_control"),
        transferable_to=("piano","guitar"),
        confidence=.91, provenance=("players/piano/texture_control.py",)),

    # ----- Bebop drummer vocabulary already encoded in Player research -----
    _item("shared.drums.ride_quarter_field",
        source_id="player:drums_ride_continuity",
        rhythm="persistent quarter-note ride field",
        articulation="ride tip",
        source_instrument="drums",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.ARTICULATION),
        domains=(LegendDomain.RHYTHM_SUBDIVISION,LegendDomain.ARTICULATION),
        tags=("jazz","bebop","ride_continuity","quarter","time"),
        transferable_to=("drums","percussion"),
        confidence=.97, provenance=("players/drums/ride_continuity.py",)),
    _item("shared.drums.skip_lift_or_omit",
        source_id="player:drums_ride_continuity",
        rhythm="swing skip note may lift or be omitted contextually",
        source_instrument="drums",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.DENSITY_ARC),
        domains=(LegendDomain.RHYTHM_SUBDIVISION,LegendDomain.BREATH_SPACE),
        tags=("jazz","bebop","skip","lift_skip","omit_skip"),
        transferable_to=("drums","percussion"),
        confidence=.96, provenance=("players/drums/ride_continuity.py",)),
    _item("shared.drums.intentional_nonresponse",
        source_id="player:drums_bebop",
        rhythm="deliberate non-response when soloist is dense/rising",
        source_instrument="drums",
        dimensions=(VocabularyDimension.INTERACTION_ROLE,VocabularyDimension.DENSITY_ARC),
        domains=(LegendDomain.ENSEMBLE_INTERACTION,LegendDomain.BREATH_SPACE),
        tags=("jazz","bebop","intentional_non_response","coast","listen"),
        transferable_to=("drums","percussion","piano","guitar"),
        confidence=.96, provenance=("players/drums/bebop.py",)),
    _item("shared.drums.snare_motif_return",
        source_id="player:drums_comping_phrase",
        rhythm="state -> space -> return/variation",
        source_instrument="drums",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.MOTIF_DEVELOPMENT,LegendDomain.REPETITION_VARIATION),
        tags=("jazz","bebop","snare_phrase","return","variation","motif"),
        transferable_to=("drums","percussion"),
        confidence=.95, provenance=("players/drums/comping_phrase.py",)),
    _item("shared.drums.displaced_return",
        source_id="player:drums_comping_phrase",
        rhythm="same rhythmic identity displaced to a new bar phase",
        source_instrument="drums",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.ACCENT),
        domains=(LegendDomain.MOTIF_DEVELOPMENT,LegendDomain.RHYTHM_SUBDIVISION),
        tags=("jazz","bebop","snare_phrase","displaced_return"),
        transferable_to=("drums","percussion","piano","bass","guitar"),
        confidence=.95, provenance=("players/drums/comping_phrase.py",)),
    _item("shared.drums.bass_drum_floor_vs_accent",
        source_id="player:drums_bebop",
        rhythm="bass drum switches between floor support and interactive accent",
        source_instrument="drums",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.INTERACTION_ROLE,VocabularyDimension.ACCENT),
        domains=(LegendDomain.ENSEMBLE_INTERACTION,LegendDomain.ARTICULATION),
        tags=("jazz","bebop","bass_drum","floor_support","interactive_accent"),
        transferable_to=("drums","percussion"),
        confidence=.93, provenance=("players/drums/bebop.py",)),
    _item("shared.drums.form_punctuation",
        source_id="player:drums_bebop",
        rhythm="setup/punctuation near phrase or form boundary",
        source_instrument="drums",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.FORM_AWARENESS,LegendDomain.PHRASE_ENDING),
        tags=("jazz","bebop","setup","punctuate","form_boundary"),
        transferable_to=("drums","percussion"),
        confidence=.94, provenance=("players/drums/bebop.py","players/drums/chorus_memory.py")),

    # Abstracted source-family knowledge. Exact source notation stays in source corpus.
    _item("shared.drums.bop_ride_24_family",
        source_id="abstracted_source:riley_art_of_bop",
        rhythm="bebop ride time with pedal hi-hat on 2 and 4",
        articulation="ride + pedal hi-hat",
        source_instrument="drums",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.ARTICULATION),
        domains=(LegendDomain.RHYTHM_SUBDIVISION,LegendDomain.ARTICULATION),
        tags=("jazz","bop","ride","pedal_hihat","2_and_4"),
        transferable_to=("drums",),
        confidence=.90, provenance=("players/drums/pattern_corpus.py","abstracted_not_literal")),
    _item("shared.drums.setup_fill_family",
        source_id="abstracted_source:spagnardi_fills",
        rhythm="short fill immediately before ensemble figure",
        source_instrument="drums",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.FORM_AWARENESS,LegendDomain.ENSEMBLE_INTERACTION),
        tags=("big_band","setup","fill","ensemble_figure"),
        transferable_to=("drums",),
        confidence=.88, provenance=("players/drums/pattern_corpus.py","abstracted_not_literal")),

    # ----- Non-reconstructive interaction/narrative abstractions from repeated
    # Bill Evans trio research. These are promoted here as generic ensemble
    # vocabulary, not as a Bill Evans imitation profile. -----
    _item("shared.ensemble.position_prior_not_command",
        source_id="research:bill_evans_trio_1000pass",
        contour="performance position informs narrative expectation but never directly selects action",
        dimensions=(VocabularyDimension.DENSITY_ARC,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.FORM_AWARENESS,LegendDomain.ENSEMBLE_INTERACTION),
        tags=("jazz","ensemble","narrative","position_prior","context_required"),
        transferable_to=("piano","bass","drums","tenor_sax","alto_saxophone","trumpet","guitar"),
        confidence=.94,
        provenance=("players/drums/BILL_EVANS_1000_PASS_STUDY.md","non_reconstructive_aggregate","user_explicit_promotion")),
    _item("shared.ensemble.opening_restraint",
        source_id="research:bill_evans_trio_1000pass",
        rhythm="clear but light opening support; preserve foreground space",
        tension_curve="restrained opening",
        dimensions=(VocabularyDimension.DENSITY_ARC,VocabularyDimension.INTERACTION_ROLE),
        domains=(LegendDomain.BREATH_SPACE,LegendDomain.ENSEMBLE_INTERACTION),
        tags=("jazz","ensemble","opening","restraint","clear_time","space"),
        transferable_to=("piano","bass","drums"),
        confidence=.90,
        provenance=("players/drums/BILL_EVANS_1000_PASS_STUDY.md","non_reconstructive_aggregate","user_explicit_promotion")),
    _item("shared.ensemble.middle_development",
        source_id="research:bill_evans_trio_1000pass",
        rhythm="later chorus development may expand activity without abandoning role clarity",
        tension_curve="development expansion",
        dimensions=(VocabularyDimension.DENSITY_ARC,VocabularyDimension.INTERACTION_ROLE),
        domains=(LegendDomain.FORM_AWARENESS,LegendDomain.ENSEMBLE_INTERACTION),
        tags=("jazz","ensemble","development","expand","chorus_history"),
        transferable_to=("piano","bass","drums","tenor_sax","alto_saxophone"),
        confidence=.91,
        provenance=("players/drums/BILL_EVANS_1000_PASS_STUDY.md","non_reconstructive_aggregate","user_explicit_promotion")),
    _item("shared.ensemble.terminal_release_conditional",
        source_id="research:bill_evans_trio_1000pass",
        rhythm="terminal contraction only when ending/narrative evidence agrees",
        tension_curve="release when justified",
        dimensions=(VocabularyDimension.DENSITY_ARC,VocabularyDimension.TENSION_RELEASE,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.PHRASE_ENDING,LegendDomain.FORM_AWARENESS,LegendDomain.TENSION_RELEASE),
        tags=("jazz","ensemble","terminal_boundary","conditional_release","ending_evidence"),
        transferable_to=("piano","bass","drums","tenor_sax","alto_saxophone"),
        confidence=.91,
        provenance=("players/drums/BILL_EVANS_1000_PASS_STUDY.md","counterexample_checked","user_explicit_promotion")),
    _item("shared.ensemble.form_knowledge_not_marking",
        source_id="research:bill_evans_trio_score_alignment",
        rhythm="known form boundary may remain unmarked",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.INTERACTION_ROLE,VocabularyDimension.PHRASE_SHAPE),
        domains=(LegendDomain.FORM_AWARENESS,LegendDomain.BREATH_SPACE),
        tags=("jazz","ensemble","form_boundary","no_fill_required","continuity"),
        transferable_to=("piano","bass","drums","tenor_sax","alto_saxophone"),
        confidence=.95,
        provenance=("players/drums/BILL_EVANS_TRIO_ROLE_STUDY_PASS3.md","score_aligned_abstraction","user_explicit_promotion")),
    _item("shared.ensemble.meter_not_pulse_responsibility",
        source_id="research:bill_evans_trio_score_alignment",
        rhythm="same nominal meter may shift felt-pulse responsibility by role/section",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.INTERACTION_ROLE),
        domains=(LegendDomain.RHYTHM_SUBDIVISION,LegendDomain.ENSEMBLE_INTERACTION),
        tags=("jazz","ensemble","pulse_role","meter","head_vs_solo","time_clarity"),
        transferable_to=("piano","bass","drums"),
        confidence=.94,
        provenance=("players/drums/BILL_EVANS_TRIO_ROLE_STUDY_PASS3.md","score_aligned_abstraction","user_explicit_promotion")),
    _item("shared.ensemble.same_form_new_chorus",
        source_id="research:bill_evans_trio_role_study",
        contour="same bar/form position may require different realization after accumulated chorus history",
        dimensions=(VocabularyDimension.PHRASE_SHAPE,VocabularyDimension.DENSITY_ARC,VocabularyDimension.INTERACTION_ROLE),
        domains=(LegendDomain.FORM_AWARENESS,LegendDomain.REPETITION_VARIATION),
        tags=("jazz","ensemble","chorus_history","same_form_new_realization","variation"),
        transferable_to=("piano","bass","drums","tenor_sax","alto_saxophone","trumpet","guitar"),
        confidence=.93,
        provenance=("players/drums/BILL_EVANS_TRIO_ROLE_STUDY_PASS2.md","players/drums/BILL_EVANS_1000_PASS_STUDY.md","user_explicit_promotion")),
    _item("shared.ensemble.foreground_role_override",
        source_id="research:bill_evans_trio_role_study",
        contour="explicit foreground reassignment can override prior restraint",
        dimensions=(VocabularyDimension.INTERACTION_ROLE,VocabularyDimension.DENSITY_ARC),
        domains=(LegendDomain.ENSEMBLE_INTERACTION,LegendDomain.FORM_AWARENESS),
        tags=("jazz","ensemble","foreground_ownership","role_override","solo_allocation"),
        transferable_to=("piano","bass","drums","tenor_sax","alto_saxophone","trumpet","guitar"),
        confidence=.93,
        provenance=("players/drums/BILL_EVANS_TRIO_ROLE_STUDY_PASS2.md","verified_role_allocation","user_explicit_promotion")),
    _item("shared.drums.time_clarifier_without_fill",
        source_id="research:bill_evans_trio_role_study",
        rhythm="clarify new pulse through cymbal/time surface rather than automatic fill",
        source_instrument="drums",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.INTERACTION_ROLE,VocabularyDimension.ARTICULATION),
        domains=(LegendDomain.RHYTHM_SUBDIVISION,LegendDomain.FORM_AWARENESS,LegendDomain.ENSEMBLE_INTERACTION),
        tags=("jazz","drums","time_clarifier","surface_change","no_fill_required"),
        transferable_to=("drums",),
        confidence=.91,
        provenance=("players/drums/BILL_EVANS_TRIO_ROLE_STUDY_PASS2.md","score_aligned_abstraction","user_explicit_promotion")),
    _item("shared.drums.bass_ambiguity_pulse_support",
        source_id="research:bill_evans_trio_role_study",
        rhythm="when bass pulse is ambiguous/counterpoint-heavy, drums may carry clearer pulse while staying light",
        source_instrument="drums",
        dimensions=(VocabularyDimension.RHYTHM,VocabularyDimension.INTERACTION_ROLE,VocabularyDimension.DENSITY_ARC),
        domains=(LegendDomain.ENSEMBLE_INTERACTION,LegendDomain.RHYTHM_SUBDIVISION),
        tags=("jazz","drums","bass_ambiguity","pulse_clarity","light_support"),
        transferable_to=("drums",),
        confidence=.88,
        provenance=("players/drums/BILL_EVANS_TRIO_ROLE_STUDY_PASS2.md","interpretation_hypothesis_promoted_as_soft_vocabulary","user_explicit_promotion")),
)


@dataclass(frozen=True)
class SharedVocabularyIndex:
    items: tuple[VocabularyMemoryItem,...]=SHARED_VOCABULARY_ITEMS

    def query(self, request: VocabularyQuery) -> tuple[VocabularyMemoryItem,...]:
        # General vocabulary is intentionally not gated by request.legend_id.
        return rank_vocabulary_items(self.items, request)


SHARED_VOCABULARY_INDEX=SharedVocabularyIndex()
